# Generated by Django 3.0.5 on 2020-04-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_forestfire_size_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestfire',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
        migrations.AlterField(
            model_name='forestfire',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=15),
        ),
    ]
