# Generated by Django 3.0.5 on 2020-04-11 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200411_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forestfire',
            name='size',
        ),
    ]
